# Copied from:
# https://github.com/omniauth/omniauth/blob/master/.travis.yml
before_install:
  - gem update --system
  - gem update bundler
cache: bundler
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - 2.5.1
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
sudo: false
